// demo/vue/m-app-test2/src/components/Footer.vue
<template>
  <div class="m-footer">
    <router-link to="/index/home" class="m-footer-item">
      <Icon type="home" class="m-footer-icon"></Icon>
      <div class="m-footer-text">首页</div>
    </router-link>
    <router-link to="/index/my_book" class="m-footer-item">
      <Icon type="shubao" class="m-footer-icon"></Icon>
      <div class="m-footer-text">书包</div>
    </router-link>
    <router-link to="/index/me" class="m-footer-item">
      <Icon type="me" class="m-footer-icon"></Icon>
      <div class="m-footer-text">我的</div>
    </router-link>        
  </div>
</template>

<script>
import Icon from '../components/Icon'

export default {
  components: {
    Icon
  }
}
</script>

<style>

</style>

// m-app-1707B/react/m-book/src/components/Footer.js
import React, { Component } from 'react'
import { NavLink } from 'react-router-dom'
import Icon from '../components/Icon'

export default class Footer extends Component {
  render() {
    return (
      <div className="m-footer">
        <NavLink to="/index/home" className="m-nav-item">
          <div><Icon type="shouye" className="m-nav-icon"></Icon></div>
          <div className="m-nav-text">首页</div>
        </NavLink>
        <NavLink to="/index/my_book" className="m-nav-item">
          <div><Icon type="shubao" className="m-nav-icon"></Icon></div>
          <div className="m-nav-text">书包</div>          
        </NavLink>
        <NavLink to="/index/me" className="m-nav-item">
          <div><Icon type="wodedangxuan" className="m-nav-icon"></Icon></div>
          <div className="m-nav-text">我的</div>             
        </NavLink>
      </div>
    )
  }
}
