// demo/ts/vue/m-app/src/views/Login.vue
<template>
  <div>
    <div>
      <input v-model="username" placeholder="请输入用户名">
    </div>
    <div>
      <input v-model="password" placeholder="请输入密码" :type="visible ? 'text' : 'password'">
      <Icon :name="visible ? 'show' : 'hide'" @onClick="handleVisible" className="m-login-icon" ></Icon>
    </div>
    <button @click="handleLogin">登录</button>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import Icon from '../components/Icon.vue'
import Api from '../api/index'

@Component({
  components: {
    Icon
  }
})
export default class Login extends Vue {
  username = 'admin'
  password = '123456'
  visible = false

  handleVisible() {
    this.visible = !this.visible
  }

  handleLogin() {
    Api.login({ username: this.username, password: this.password }).then(res => {
      if (res.code === 200) {
        localStorage.setItem('token', res.data.username);
        (this as any).$router.push('/index/home')
        console.log((this as any).$store.state.count)
      }
    })
  }
}
</script>

<style>

</style>

// demo/ts/react/m-app-test/src/views/Login.tsx
import React, { useState, KeyboardEvent } from 'react'
import { RouteComponentProps } from 'react-router-dom'
import Api from '../api'
import Icon from '../components/Icon'

interface IProps extends RouteComponentProps {

}

const Login = (props: IProps) => {
  const [ username, setUsername ] = useState('admin')
  const [ password, setPassword  ] = useState('123456')
  const [ visible, setVisible ] = useState(false)

  const handleVisible = () => {
    setVisible(!visible)
  }

  const handleLogin = () => {
    Api.login({ username, password }).then(res => {
      if (res.code === 200) {
        console.log(res.data)
        props.history.push('/index')
      }
    })
  }

  const handleEnter = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.keyCode === 13) {
      handleLogin()
    }
  }

  return (
    <div>
      <div>
        <input type="text" value={username} onChange={(e) => setUsername(e.target.value)} placeholder="请输入用户名" autoFocus />
      </div>
      <div>
        <input type={ visible ? "text" : "password" } value={password} onChange={(e) => setPassword(e.target.value)} onKeyUp={(e) => handleEnter(e)} placeholder="请输入密码" />
        <Icon name={ visible ? "show" : "hide"} className="m-login-icon" onClick={() => handleVisible()}></Icon>
      </div>
      <button onClick={() => handleLogin()} >登录</button>
    </div>
  )
}

export default Login
