// demo/vue/m-app2/src/views/Home.vue
<template>
  <div class="m-main m-home">
    <Sidebar></Sidebar>
    <List></List>
  </div>
</template>

<script>
import Sidebar from '../components/Sidebar'
import List from '../components/List'

export default {
  components: {
    Sidebar,
    List
  },
  mounted() {
    this.$store.dispatch({ type: 'getList' })
  }
}
</script>

<style>

</style>

// m-app-1708E/react/m-app-test/src/views/Home.js
import React, { Component } from 'react'
import Sidebar from '../components/Sidebar'
import List from '../components/List'

export default class Home extends Component {
  render() {
    return (
      <div className="m-main m-home">
        <Sidebar></Sidebar>
        <List></List>
      </div>
    )
  }
}
