// demo/vue/m-app2/src/views/Login.vue
<template>
  <div>
    <div>
      <input v-model="username" placeholder="请输入用户名" autofocus >
    </div>
    <div>
      <input v-model="password" placeholder="请输入密码" :type=" visible ? 'text' : 'password'" @keyup.enter="handleLogin" >
      <Icon :name="visible ? 'xianshimima' : 'buxianshimima'" class="m-login-icon" @onClick="handleVisible" ></Icon>
    </div>
    <button @click="handleLogin">登录</button>
  </div>
</template>

<script>
import axios from 'axios'
import Icon from '../components/Icon'
import Api from '../api'

export default {
  data() {
    return {
      username: 'admin',
      password: '123456',
      visible: false
    }
  },
  components: {
    Icon
  },
  methods: {
    handleLogin() {
      Api.login({ username: this.username, password: this.password }).then(res => {
        if (res.code === 200) {
          localStorage.setItem('token', res.data.username)
          this.$router.push('/index/home')
        }
      })
    },
    handleVisible() {
      this.visible = !this.visible
    }
  }
}
</script>

<style>

</style>

// m-app-1708E/react/m-app-test/src/views/Login.js
import React, { Component } from 'react'
import Api from '../api'
import Icon from '../components/Icon'

export default class Login extends Component {
  constructor(props) {
    super(props)
    this.state = {
      username: 'admin',
      password: '123456',
      visible: false
    }
  }

  handleInput(field, e) {
    this.setState({
      [field]: e.target.value
    })
  }

  handleVisible() {
    this.setState({
      visible: !this.state.visible
    })
  }

  handleLogin() {
    let { username, password } = this.state
    Api.login({ username, password }).then(res => {
      if (res.code === 200) {
        this.props.history.push('/index/home')
      }
    })
  }

  handleEnter(e) {
    if (e.keyCode === 13) {
      this.handleLogin()
    }
  }

  render() {
    let { username, password, visible } = this.state
    return (
      <div>
        <div>
          <input value={username} onChange={this.handleInput.bind(this, 'username')} placeholder="请输入用户名" autoFocus></input>
        </div>
        <div>
          <input 
            value={password} 
            onChange={this.handleInput.bind(this, 'password')} 
            onKeyUp={this.handleEnter.bind(this)}
            placeholder="请输入密码" type={ visible ? 'text' : "password"}></input>
          <Icon 
            className="m-login-icon"
            type={ visible ?  'xianshimima' : "buxianshimima" } 
            onClick={this.handleVisible.bind(this)}></Icon>
        </div>
        <button onClick={this.handleLogin.bind(this)}>登录</button>
      </div>
    )
  }
}
