// demo/ts/vue/m-app-tslint/src/views/Detail.vue
<template>
  <div>
    <DetailHeader :title="book.title"></DetailHeader>
    <div class="m-detail-img-wrap">
      <img :src="book.avatar">
    </div>
    <div class="m-detail-add-info">
      <button class="m-btn" @click="handleSub">减</button>
      <input type="text" :value="book.count" placeholder="数量" class="m-input" @input="handleInput">
      <button class="m-btn" @click="handleAdd" >加</button>
      <button class="m-btn" @click="handleAddToMyBooks">添加</button>
    </div>    
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { Action } from 'vuex-class'
import DetailHeader from '../components/DetailHeader.vue'
import Api from '../api'

@Component({
  components: {
    DetailHeader
  }
})
export default class Detail extends Vue {
  @Action('myBooksAction') myBooksAction!: Function

  book:any = { count: 1 }

  handleSub() {
    if (this.book.count > 1) {
      this.book.count--
    }
  }
  handleAdd() {
    this.book.count++
  }

  handleInput(e:any) {
    let count = e.target.value.replace(/[^\d]/g, '') - 0
    if (count === 0) {
      count = 1
    }      
    this.book = { ...this.book, count }
  }
  handleAddToMyBooks() {
    this.book.checked = true
    this.myBooksAction({ data: { book: this.book }, method: 'post',  callback: () => {
      (this as any).$router.push('/index/my_books')
    }})
  }

  mounted() {
    let { id } = (this as any).$route.params
    Api.getDetail(id).then(res => {
      if (res.code === 200) {
        let book = res.data
        book.count = 1
        this.book = res.data
      }
    })
  }
}
</script>

<style>

</style>

// demo/ts/react/react-ts-app/src/views/Detail.tsx
import React, { useState, useEffect, ChangeEvent, Dispatch } from 'react'
import { RouteComponentProps } from 'react-router-dom'
import { connect } from 'react-redux'
import DetailHeader from '../components/DetailHeader'
import Api from '../api'
import actionCreator from '../store/book/actionCreator'

interface IProps extends RouteComponentProps {
  onDispatch(action: Function):void
}

const Detail = (props: IProps ) => {
  let [ book, setBook ] = useState<any>({ count: 1}) 

  const handleSub = () => {
    if (book.count > 1) {
      book.count--
      setBook({...book})
    }
  }

  const handleAdd = () => {
    book.count++
    setBook({...book})
  }

  const handleAddToMyBook = () => {
    props.onDispatch(actionCreator.myBooks({ book }, 'post', () => {
      props.history.push('/index/my_books')
    }))
  }

  const handleInput = (e: ChangeEvent<HTMLInputElement>) => {
    let count = parseInt(e.target.value.replace(/[^\d]/g, ''))
    if (count === 0) {
      count = 1
    }
    book.count = count
    setBook({...book})
  }


  useEffect(() => {
    //@ts-ignore
    let { id } = props.match.params
    Api.getDetail(id).then(res =>  {
      if (res.code === 200) {
        let book = res.data
        book.count = 1
        book.checked = true
        setBook(book)
      }
    })
  }, [props])
  
  return (
    <div>
      <DetailHeader title={book.title}></DetailHeader>
      <div className="m-detail-img-wrap">
        <img src={book.avatar} alt={book.title}></img>
      </div>
      <div>
        <div className="m-add-info">
          <button className="m-btn" onClick={() => handleSub()}>-</button>
          <input value={book.count} placeholder="数量" className="m-input" onChange={(e) => handleInput(e)} ></input>
          <button className="m-btn" onClick={() => handleAdd()} >+</button>
          <button className="m-btn" onClick={() => handleAddToMyBook()}>添加</button>
        </div>
      </div>
    </div>
  )
}

const mapDispatchToProps = (dispatch: Dispatch<any>) => {
  return {
    onSetState(key: string, value: any) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    onDispatch(action: Function) {
      dispatch(action)
    }
  }
}

export default connect(null, mapDispatchToProps)(Detail)
