// demo/ts/vue/m-app-tslint/src/views/Login.vue
<template>
  <div>
    <div>
      <input v-model="username" placeholder="请输入用户名">
    </div>
    <div>
      <input v-model="password" placeholder="请输入密码" :type="visible ? 'text' : 'password'">
      <Icon :name="visible ? 'show' : 'hide'" @onClick="handleVisible" className="m-login-icon" ></Icon>
    </div>
    <button @click="handleLogin">登录</button>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import Icon from '../components/Icon.vue'
import Api from '../api'

@Component({
  components: {
    Icon
  }
})
export default class Login extends Vue {
  username = 'admin'
  password = '123456'
  visible = false

  handleVisible() {
    this.visible = !this.visible
  }

  handleLogin() {
    Api.login({ username: this.username, password: this.password }).then(res => {
      if (res.code === 200) {
        localStorage.setItem('token', res.data.username);

        //@ts-ignore
        this.$router.push('/index/home')
        console.log((this as any).$store.state.count)
      }
    })
  }
}
</script>

<style>

</style>

// demo/ts/react/react-ts-app/src/views/Login.tsx
import React, { useState, MouseEvent, KeyboardEvent } from 'react'
import { RouteComponentProps } from 'react-router-dom'
import Icon from '../components/Icon'
import Api from '../api'

const Login = (props: RouteComponentProps) => {
  const [ username, setUsername ] = useState('admin')
  const [ password, setPassword ] = useState('123456')
  const [ visible, setVisible ] = useState(false)

  const handleVisible = (e: MouseEvent, count: number ) => {
    setVisible(!visible)
  }

  const handleEnter = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.keyCode === 13 ) {
      handleLogin()
    }
  }

  const handleLogin = () => {
    Api.login({ username, password }).then(res => {
      if (res.code === 200) {
        localStorage.setItem('token', res.data.username)
        props.history.push('/index/home')
      }
    })
  }

  return (
    <div>
      <div>
        <input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="请输入用户名" autoFocus></input>
      </div>
      <div>
        <input value={password} onChange={(e) => setPassword(e.target.value)} onKeyUp={ (e) => handleEnter(e)  } placeholder="请输入密码" type={ visible ? 'text' : 'password' }></input>
        <Icon name={ visible ? 'show' : 'hide' } onClick={ (e, count) => handleVisible(e, count) } className="m-login-icon"></Icon>
      </div>
      <button onClick={() => handleLogin()}>登录</button>
    </div>
  )
}

export default Login
