// demo/ts/vue/m-app-tslint/src/views/MyBooks.vue
<template>
  <div class="m-main">
    <div class="m-my-books" v-if="myBooks.length > 0">
      <div class="m-my-books-content">
        <MyBookItem
          v-for="book in myBooks" 
          :key="book.id" 
          :book="book">
        </MyBookItem>
      </div>
      <div class="m-my-books-footer">
        <label>
          <input type="checkbox" :checked="total.checkedAll" @click="handleCheckedAll">
          全选
        </label>
        <button @click="handleShowDialog">删除</button>
        <span>
          合计: ￥{{total.totalPrice}}
        </span>
      </div>
    </div>
    <div v-else class="m-my-books-empty">
      购物车空空如也~
    </div>
    <Dialog title="删除" :visible="visible" @onCancel="handleCancel" @onOk="handleDeleteChecked">
      <template v-slot:content>
        <div class="m-my-books-delete-dialog-info">
          您确定要删除选中的商品吗？
        </div>
      </template>
    </Dialog>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { State, Action } from 'vuex-class'
import Dialog from '../components/Dialog.vue'
import MyBookItem from '../components/MyBookItem.vue'

@Component({
  components: {
    Dialog,
    MyBookItem
  }
})
export default class extends Vue {
  @State(state => state.myBooks) myBooks!: any[]
  @Action('myBooksAction') myBooksAction!: Function

  visible = false

  get total() {
    return {
      totalPrice: this.myBooks.reduce((total, item) => total + item.count * item.price, 0),
      checkedAll: this.myBooks.every(item => item.checked)
    }
  }

  handleCheckedAll(e:any) {
    this.myBooksAction({ data: { operation: 'checkedAll', checked: e.target.checked }, method: 'patch' })
  }
  handleShowDialog() {
    let myBooks = this.myBooks
    if (myBooks.filter(item => item.checked).length === 0) {
      //this.$message({ message: '请选择要删除的商品哦~', duration: 2000 })
      alert('请选择要删除的商品哦~')
    } else {
      this.visible = true
    }
  }
  handleDeleteChecked() {
    let ids = this.myBooks.filter(item => item.checked).map(item => item.id)
    this.myBooksAction({ data: { ids }, method: 'delete', callback: () => {
      this.handleCancel()
    }})
  }
  handleCancel() {
    this.visible = false
  }
}
</script>

<style>

</style>

// demo/ts/react/react-ts-app/src/views/MyBooks.tsx
import React, { useState, Dispatch, ChangeEvent } from 'react'
import { connect } from 'react-redux'
import { IStore, IBook } from '../types'
import actionCreator from '../store/book/actionCreator'
import MyBookItem from '../components/MyBookItem'
import Dialog from '../components/Dialog'

interface IProps {
  myBooks: IBook[],
  onSetState: (key: string, value: any) => void
  onDispatch: (action: Function) => void
}
const MyBooks = (props: IProps) => {
  let { myBooks, onDispatch } = props
  const [ visible, setVisible ] = useState(false)

  const handleShowDialog = () => {
    if (myBooks.filter(item => item.checked).length === 0) {
      //this.$message({ message: '请选择要删除的商品哦~', duration: 2000 })
      alert('请选择要删除的商品哦~')
    } else {
      setVisible(true)
    }
  }

  const handleCancel = () => {
    setVisible(false)
  }

  const handleDeleteChecked = () => {
    let ids = myBooks.filter(item => item.checked).map(item => item.id)
    onDispatch(actionCreator.myBooks({ ids }, 'delete', () => {
      handleCancel()
    } ))
  }

  const handleCheckedAll = (e: ChangeEvent<HTMLInputElement>) => {
    onDispatch(actionCreator.myBooks({ operation: 'checkedAll', checked: e.target.checked }, 'patch' ))
  }

  let totalPrice = myBooks.filter(item => item.checked).reduce((total, item) => total + item.count * item.price, 0)
  let checkedAll = myBooks.every(item => item.checked)

  let bookListDom = myBooks.map(item => (
    <MyBookItem key={item.id} book={item}></MyBookItem>
  ))

  return (
    <div className="m-main">
      {
        myBooks.length > 0 ?
        <div className="m-my-books">
          <div className="m-my-books-content">
            {bookListDom}
          </div>
          <div className="m-my-books-footer">
            <label>
              <input type="checkbox" checked={checkedAll} onChange={ (e) => handleCheckedAll(e)}/>
              <span>全选</span>
            </label>
            <button onClick={ () => handleShowDialog() }>删除</button>
            <span>
              合计: ￥{totalPrice}
            </span>
          </div>
        </div>
        :
        <div className="m-my-books-empty">
          购物车空空如也~
        </div>
      }
      <Dialog visible={visible} title="删除" onOk={() => handleDeleteChecked()} onCancel={() => handleCancel()}>
        <div className="m-my-books-delete-dialog-info">
          您确定要删除选中的商品吗？
        </div>
      </Dialog>
    </div>
  )
}

const mapStateToProps = (state: IStore) => {
  return {
    myBooks: state.book.myBooks
  }
}

const mapDispatchToProps = (dispatch: Dispatch<any>) => {
  return {
    onSetState(key: string, value: any) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    onDispatch(action: Function) {
      dispatch(action)
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(MyBooks)
