// m-app-1708E/m-app/src/views/MyBook.vue
<template>
  <div>
    <div v-for="(item, index) in myBook" :key="item.id" class="m-my-book-item">
      <div class="m-my-book-info">
        <label>
          <input type="checkbox" :checked="item.checked" @change="handleCheck(index, $event)" />
          {{item.title}}
        </label>
        ￥{{item.price}}
      </div>
      <div class="m-my-book-action">
        <button @click="handleSub(index)">-</button>
        {{item.count}}
        <button @click="handleAdd(index)">+</button>
        <button @click="handleDelete(index)">删除</button>
      </div>
    </div>
    <div v-if="myBook.length > 0">
      <div>
        <label>
          <input type="checkbox" :checked="total.checkedAll" @click="handleCheckAll">
          全选
        </label>
        <button @click="handleShowDialog">删除</button>
      </div>
      <div>总价：￥{{total.totalPrice}},总数：{{total.totalCount}}</div>
    </div>
    <div v-else>书包空空如也~~~</div>
    <Dialog :visible="visible" title="删除">
      <template v-slot:content>
        <div class="m-delete-info">
          <Icon type="shanchu" classname="m-delete-icon"></Icon>
          <div class="m-delete-text">
            你确定要删除选中的商品吗？
          </div>
        </div>
      </template>
      <template v-slot:footer>
        <button class="m-btn" @click="handleHideDialog">取消</button>
        <button class="m-btn" @click="handleDeleteChecked">确定</button>
      </template>
    </Dialog>
  </div>
</template>

<script>
import Api from "../api";
import Dialog from '../components/Dialog'
import Icon from '../components/Icon'
import toast from '../components/Toast'

export default {
  data() {
    return {
      visible: false
    }
  },
  computed: {
    myBook() {
      return this.$store.state.myBook;
    },
    total() {
      let myBook = this.myBook;
      let totalCount = myBook.filter(item => item.checked).reduce((total, item) => {
        return total + item.count;
      }, 0);
      let totalPrice = myBook.filter(item => item.checked).reduce((total, item) => {
        return total + item.count * item.price;
      }, 0);
      return {
        totalCount,
        totalPrice,
        checkedAll: myBook.every(item => item.checked)
      };
    }
  },
  components:{
    Dialog,
    Icon
  },
  methods: {
    handleSub(index) {
      let myBook = this.myBook;
      if (myBook[index].count > 1) {
        myBook[index].count--;
        this.$store.commit({ type: "setState", key: "myBook", value: myBook });
      }
    },
    handleAdd(index) {
      let myBook = this.myBook;
      myBook[index].count++;
      this.$store.commit({ type: "setState", key: "myBook", value: myBook });
    },
    handleDelete(index) {
      let myBook = this.myBook;
      myBook.splice(index, 1)
      this.$store.commit({ type: "setState", key: "myBook", value: myBook });
    },
    handleCheck(index, e) {
      let myBook = this.myBook;
      myBook[index].checked = e.target.checked
      this.$store.commit({ type: "setState", key: "myBook", value: myBook });
    },
    handleCheckAll(e) {
      let myBook = this.myBook;
      myBook.forEach(item => {
        item.checked = e.target.checked
      })
      this.$store.commit({ type: "setState", key: "myBook", value: myBook });
    },
    handleDeleteChecked() {
      let myBook = this.myBook;
      myBook = myBook.filter(item => !item.checked)
      this.$store.commit({ type: "setState", key: "myBook", value: myBook });
      this.handleHideDialog()
    },
    handleShowDialog() {
      if (this.myBook.filter(item => item.checked).length === 0) {
        //alert('请选择要删除的商品~')
        //toast({message: '请选择要删除的商品~', duration: 1000})
        this.$toast({message: '请选择要删除的商品~'})
        return
      }
      this.visible = true
    },
    handleHideDialog() {
      this.visible = false
    }
  },
  updated() {
    Api.update({ myBookNew: this.myBook }).then(res => {});
  },
  mounted() {
    this.$store.dispatch({ type: "getMyBook" });
  }
};
</script>

<style>
</style>

// m-app-1707B/react/m-book/src/views/MyBook.js
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { fromJS, is } from 'immutable'
import { message } from 'antd'
import actionCreator from '../store/actionCreator'
import Dialog from '../components/Dialog'


let myBookHistory = []
class MyBook extends Component {
  constructor(props) {
    super(props)
    this.state = {
      visible: false
    }
  }
  handleCheck(index, e) {
    let { myBook } = this.props
    myBook[index].checked = e.target.checked
    this.props.onSetState(['myBook'], myBook)
  }
  handleSelectAll(e) {
    let { myBook } = this.props
    myBook.forEach(item => {
      item.checked = e.target.checked
    })
    this.props.onSetState(['myBook'], myBook)
  }
  handleSub(index) {
    let { myBook } = this.props
    if (myBook[index].count > 1) {
      myBook[index].count--
      this.props.onSetState(['myBook'], myBook)
    }
  }
  handleAdd(index) {
    let { myBook } = this.props
    myBook[index].count++
    this.props.onSetState(['myBook'], myBook)
  }
  handleCount(index, e) {
    let { myBook } = this.props
    myBook[index].count = e.target.value.replace(/[^0-9]/g, '') * 1
    this.props.onSetState(['myBook'], myBook)
  }
  handleDelete(index) {
    let { myBook } = this.props
    myBook.splice(index, 1)
    this.props.onSetState(['myBook'], myBook)
  }
  handleShowDialog() {
    let { myBook } = this.props
    if (myBook.filter(item => item.checked).length > 0) {
      this.setState({
        visible: true
      })
    } else {
      message.info('请选择要删除的商品~')
    }
  }
  handleHideDialog() {
    this.setState({
      visible: false
    })
  }
  handleDeleteSelected() {
    let { myBook } = this.props
    this.props.onSetState(['myBook'], myBook.filter(item => !item.checked))
    this.handleHideDialog()
  }
  componentDidUpdate() {
    let { myBook } = this.props
    if (is(fromJS(myBookHistory), fromJS(myBook))) {
      console.log(2)
    } else {
      console.log(1)
      this.props.onDispatch(actionCreator.updateMyBook(myBook))
      myBookHistory = MyBook
    }
  }
  render() {
    let { myBook } = this.props
    let { visible } = this.state
    let totalPrice = 0, totalCount = 0
    myBook.filter(item => item.checked).forEach(item => {
      totalPrice += item.count * item.price
      totalCount += item.count
    })
    let count = myBook.filter(item => item.checked).length
    let selectedAll = count == myBook.length && count > 0
    let myBookDom = myBook.map((item, index) => (
      <div key={item.id} className="m-my-book-item">
        <div className="m-my-book-info">
          <label>
            <input type="checkbox" checked={item.checked} onChange={this.handleCheck.bind(this, index)}></input>
            {item.title}
          </label>
          ￥{item.price}
        </div>
        <div className="m-my-book-action">
          <button onClick={this.handleSub.bind(this, index)} className="m-btn">-</button>
          <input placeholder="请输入" value={item.count} className="m-add-count" onChange={this.handleCount.bind(this, index)} type="text"></input>
          <button onClick={this.handleAdd.bind(this, index)} className="m-btn">+</button>
          <button onClick={this.handleDelete.bind(this, index)}>删除</button>
        </div>
      </div>
    ))
    return (
      <div className="m-main m-my-book">
        {myBookDom}
        {
          myBook.length > 0 &&
          <div>
            <div>
              <label>
                <input type="checkbox" checked={selectedAll} onChange={this.handleSelectAll.bind(this)}></input>
                全选
            </label>
              <button onClick={this.handleShowDialog.bind(this)}>删除</button>
            </div>
            <div>
              总价：￥{totalPrice}，总数：{totalCount}
            </div>
          </div>
        }
        <Dialog
          title="删除"
          visible={visible}
          onCancel={this.handleHideDialog.bind(this)}
          onOk={this.handleDeleteSelected.bind(this)}
        >
          <div className="m-delete-msg">你确定要删除选中的商品吗？</div>
        </Dialog>
      </div>
    )
  }
}

//相当于vue里的computed计算属性获取store里的数据
const mapStateToProps = (state) => {
  state = state.toJS()
  return {
    listAll: state.listAll,
    currentId: state.currentId,
    myBook: state.myBook
  }
}

//onSetState相当于vuex里的commit提交mutation， onDispatcg相当于vuex里的dispatch提交action
const mapDispatchToProps = (dispatch) => {
  return {
    onSetState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    onDispatch(action) {
      dispatch(action)
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(MyBook)
