// m-app-1707B/m-book-test/src/views/MyBook.vue
<template>
  <div>
    <div v-for="(item, index) in myBook" :key="item.id">
      <input
        type="checkbox"
        :checked="item.checked"
        :id="item.id"
        @change="handleChecked(index, $event)"
      />
      <label :for="item.id">{{item.title}}</label>
      ￥{{item.price}}
      <button @click="handleSub(index)">-</button>
      {{item.count}}
      <button @click="handleAdd(index)">+</button>
      <button @click="handleDelete(item.id)">删除</button>
    </div>
    <div>
      <input type="checkbox" id="all" :checked="total.selectedAll" @change="handleSelectAll" />
      <label for="all">全选</label>
      <button @click="handleShowDialog">删除</button>
    </div>
    <div>总价：￥{{total.totalPrice}}，总数：{{total.totalCount}}</div>
    <Dialog :visible="visible" title="删除">
      <div>
        你确定要删除选中的图书吗？
      </div>
      <template v-slot:footer>
        <button @click="handleHideDialog">取消</button>
        <button @click="handleDeleteSelected">确定</button>
      </template>
    </Dialog>
  </div>
</template>

<script>
import Dialog from '../components/Dialog'

export default {
  data() {
    return {
      visible: false
    }
  },
  computed: {
    myBook() {
      console.log('更新')
      return this.$store.state.myBook;
    },
    total() {
      let totalPrice = 0,
        totalCount = 0;
      let myBook = this.$store.state.myBook;
      myBook
        .filter(item => item.checked)
        .forEach(item => {
          totalCount += item.count;
          totalPrice += item.count * item.price;
        });
      let count = myBook.filter(item => item.checked).length;
      return {
        totalPrice,
        totalCount,
        selectedAll: count === myBook.length && myBook.length > 0  //每一本书选择状态改变时，全选复选框状态联动
      };
    }
  },
  components: {
    Dialog
  },
  methods: {
    //删除
    handleDelete(id) {
      let index = this.myBook.findIndex(item => item.id === id);
      this.myBook.splice(index, 1);
      this.$store.commit({
        type: "setState",
        key: "myBook",
        value: [...this.myBook]
      });
    },
    //加
    handleAdd(index) {
      this.myBook[index].count++;
      this.$store.commit({
        type: "setState",
        key: "myBook",
        value: [...this.myBook]
      });
    },
    //减
    handleSub(index) {
      if (this.myBook[index].count > 1) {
        this.myBook[index].count--;
        this.$store.commit({
          type: "setState",
          key: "myBook",
          value: [...this.myBook]
        });
      }
    },
    //复选框
    handleChecked(index, e) {
      let myBook = this.myBook
      myBook[index].checked = e.target.checked;
      this.$store.commit({
        type: "setState",
        key: "myBook",
        value: [...myBook]
      });
    },
    //联动，全选控制上面的每一项
    handleSelectAll(e) {
      let myBook = this.myBook;
      myBook.forEach(item => {
        item.checked = e.target.checked;
      });
      this.$store.commit({
        type: "setState",
        key: "myBook",
        value: [...this.myBook]
      });
    },
    //删除选中的
    handleDeleteSelected() {
      let myBook = this.myBook;
      myBook = myBook.filter(item => !item.checked);
      this.$store.commit({
        type: "setState",
        key: "myBook",
        value: [...myBook]
      });
      this.handleHideDialog()
    },
    handleShowDialog() {
      this.visible = true
    },
    handleHideDialog() {
      this.visible = false
    }
  },
  updated() {
    //每次更新完，都会往后端存一份，刷新时就不会丢了
    this.$store.dispatch({ type: "update" });
  },
  mounted() {
    //刷新时会再获取一遍后端的数据
    this.$store.dispatch({ type: "getMyBook" });
  }
};
</script>

<style>
</style>

// m-app-1707B/react/m-book/src/views/MyBook.js
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { fromJS, is } from 'immutable'
import { message } from 'antd'
import actionCreator from '../store/actionCreator'
import Dialog from '../components/Dialog'


let myBookHistory = []
class MyBook extends Component {
  constructor(props) {
    super(props)
    this.state = {
      visible: false
    }
  }
  handleCheck(index, e) {
    let { myBook } = this.props
    myBook[index].checked = e.target.checked
    this.props.onSetState(['myBook'], myBook)
  }
  handleSelectAll(e) {
    let { myBook } = this.props
    myBook.forEach(item => {
      item.checked = e.target.checked
    })
    this.props.onSetState(['myBook'], myBook)
  }
  handleSub(index) {
    let { myBook } = this.props
    if (myBook[index].count > 1) {
      myBook[index].count--
      this.props.onSetState(['myBook'], myBook)
    }
  }
  handleAdd(index) {
    let { myBook } = this.props
    myBook[index].count++
    this.props.onSetState(['myBook'], myBook)
  }
  handleCount(index, e) {
    let { myBook } = this.props
    myBook[index].count = e.target.value.replace(/[^0-9]/g, '') * 1
    this.props.onSetState(['myBook'], myBook)
  }
  handleDelete(index) {
    let { myBook } = this.props
    myBook.splice(index, 1)
    this.props.onSetState(['myBook'], myBook)
  }
  handleShowDialog() {
    let { myBook } = this.props
    if (myBook.filter(item => item.checked).length > 0) {
      this.setState({
        visible: true
      })
    } else {
      message.info('请选择要删除的商品~')
    }
  }
  handleHideDialog() {
    this.setState({
      visible: false
    })
  }
  handleDeleteSelected() {
    let { myBook } = this.props
    this.props.onSetState(['myBook'], myBook.filter(item => !item.checked))
    this.handleHideDialog()
  }
  componentDidUpdate() {
    let { myBook } = this.props
    if (is(fromJS(myBookHistory), fromJS(myBook))) {
      console.log(2)
    } else {
      console.log(1)
      this.props.onDispatch(actionCreator.updateMyBook(myBook))
      myBookHistory = MyBook
    }
  }
  render() {
    let { myBook } = this.props
    let { visible } = this.state
    let totalPrice = 0, totalCount = 0
    myBook.filter(item => item.checked).forEach(item => {
      totalPrice += item.count * item.price
      totalCount += item.count
    })
    let count = myBook.filter(item => item.checked).length
    let selectedAll = count == myBook.length && count > 0
    let myBookDom = myBook.map((item, index) => (
      <div key={item.id} className="m-my-book-item">
        <div className="m-my-book-info">
          <label>
            <input type="checkbox" checked={item.checked} onChange={this.handleCheck.bind(this, index)}></input>
            {item.title}
          </label>
          ￥{item.price}
        </div>
        <div className="m-my-book-action">
          <button onClick={this.handleSub.bind(this, index)} className="m-btn">-</button>
          <input placeholder="请输入" value={item.count} className="m-add-count" onChange={this.handleCount.bind(this, index)} type="text"></input>
          <button onClick={this.handleAdd.bind(this, index)} className="m-btn">+</button>
          <button onClick={this.handleDelete.bind(this, index)}>删除</button>
        </div>
      </div>
    ))
    return (
      <div className="m-main m-my-book">
        {myBookDom}
        {
          myBook.length > 0 &&
          <div>
            <div>
              <label>
                <input type="checkbox" checked={selectedAll} onChange={this.handleSelectAll.bind(this)}></input>
                全选
            </label>
              <button onClick={this.handleShowDialog.bind(this)}>删除</button>
            </div>
            <div>
              总价：￥{totalPrice}，总数：{totalCount}
            </div>
          </div>
        }
        <Dialog
          title="删除"
          visible={visible}
          onCancel={this.handleHideDialog.bind(this)}
          onOk={this.handleDeleteSelected.bind(this)}
        >
          <div className="m-delete-msg">你确定要删除选中的商品吗？</div>
        </Dialog>
      </div>
    )
  }
}

//相当于vue里的computed计算属性获取store里的数据
const mapStateToProps = (state) => {
  state = state.toJS()
  return {
    listAll: state.listAll,
    currentId: state.currentId,
    myBook: state.myBook
  }
}

//onSetState相当于vuex里的commit提交mutation， onDispatcg相当于vuex里的dispatch提交action
const mapDispatchToProps = (dispatch) => {
  return {
    onSetState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    onDispatch(action) {
      dispatch(action)
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(MyBook)
