// demo/ts/vue/m-app-tslint/src/components/Stars.vue
<template>
  <div>
    <Icon v-for="n in 5" :key="n" name="star" :class="[`m-star ${n <= count ? 'active' : ''}`]"></Icon>
  </div>
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator'
import Icon from './Icon.vue'

@Component({
  components: {
    Icon
  }
})
export default class Stars extends Vue {
  @Prop() count!:number
}
</script>

<style>

</style>

// demo/ts/react/react-ts-app/src/components/Stars.tsx
import React from 'react'
import Icon from './Icon'

interface IProps {
  count: number
}

const Stars = (props: IProps) => {
  let { count } = props

  const starsDom = []
  for (let i = 0; i < 5; i++) {
    starsDom.push(<Icon name="star" key={i} className={`m-star ${ i < count ? 'active' : '' }`}></Icon>)
  }

  return (
    <div>
      {starsDom}
    </div>
  )
}

export default Stars
