// m-app-1708E/react/m-app-test2/src/components/List.js
import React from 'react'
import { connect } from 'react-redux'

const List = (props) => {
  let { listAll } = props
  let listDom = listAll.map(category => (
    <div key={category.id}>
      <div className="m-category-title">
        {category.title}
      </div>
      
      {
        category.list.map(book => (
          <div key={book.id} className="m-list-item">
            <div className="m-list-img-wrap">
              <img src={book.avatar} className="m-list-img"></img>
            </div>
            <div className="m-list-info">{book.title}</div>
          </div>
        ))
      }
    </div>
  ))
  return (
    <div className="m-list">
      {listDom}
    </div>
  )
}

//取全局store里的数据
const mapStateToProps = (state) => {
  return {
    listAll: state.getIn(['listAll']).toJS(),
    currentId: state.getIn(['currentId'])
  }
}

//改全局store里的数据
const mapDispatchToProps = (dispatch) => {
  return {
    //同步
    onSetState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    //异步
    onDispatch(action) {
      dispatch(action)
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(List)

// m-app-1707B/任务/src/components/List.vue
<template>
  <div>
    <div v-for="item in list" :key="item.id" class="m-list-item">
      <div class="m-img-wrap">
        <img v-lazy="item.avatar" class="m-img">
      </div>
      <div class="m-task-info">
        {{item.title}}
      </div>
    </div>
  </div>
</template>

<script>
export default {
  computed: {
    list() {
      return this.$store.state.currentList
    }
  }
}
</script>

<style>

</style>
