// m-app-1708E/react/m-app/src/views/Detail.js
import React, { useState, useEffect } from 'react'
import Api from '../api'
import CommonHeader from '../components/CommonHeader'

const Detail = (props) => {
  let [ detail, setDetail ] = useState({})
  let [ id, setId ] = useState(props.match.params.id)

  const handleUpdateId = () => {
    setId(id === '7404' ? '1009' : '7404')
  }

  
  useEffect(() => {
    Api.getDetail(`/${id}`).then(res => {
      if (res.code === 200) {
        setDetail(res.data)
      }
    })
  }, [id])

  return (
    <div className="m-wrap">
      <CommonHeader title={detail.title}></CommonHeader>
      <div className="m-detail">
        <img src={detail.avatar} alt={detail.title} width='225' height='300'></img>
        <div>
          <button onClick={handleUpdateId}>测试</button>
        </div>
      </div>
    </div>
  )
}

export default Detail

// demo/vue/m-app2/src/views/Detail.vue
<template>
  <div>
    <DetailHeader :title="detail.title"></DetailHeader>
    <div class="m-detail-img-wrap">
      <img :src="detail.avatar" >
    </div>
    
  </div>
</template>

<script>
import DetailHeader from '../components/DetailHeader'
import Api from '../api'

export default {
  data() {
    return {
      detail: {}
    }
  },
  components: {
    DetailHeader
  },
  mounted() {
    let { id } = this.$route.params
    Api.detail(id).then(res => {
      if (res.code === 200) {
        this.detail = res.data
      }
    })
  }
}
</script>

<style>

</style>
