// m-app-1708E/m-app/src/components/Toast/Toast.vue
<template>
  <div class="m-toast-mask" :id="id" >
    <div class="m-toast">{{message}}</div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      duration: 3000,
      message: '',
      id: Date.now()
    }
  },
  mounted() {
    setTimeout(() => {
      //document.getElementById(this.id).remove()
      document.body.removeChild(document.getElementById(this.id))
    }, this.duration)
  }
}
</script>

<style>

</style>

// m-app-1708E/react/02开发npm包/src/components/toast/index.js
import React from 'react'
import ReactDOM, { createPortal } from 'react-dom'
import Toast from './Toast'

const toast = (config = {}) => {
  let dom = document.createElement('div')
  document.body.appendChild(dom)

  setTimeout(() => {
    dom.remove()
    config.onClose && config.onClose()
  }, config.duration || 150000)

  ReactDOM.render(
    <Toast {...config}></Toast>,
    dom
  )
}

export {
  toast
}
