// m-app-1707B/m-book-new/src/components/Dialog.vue
<template>
  <div class="m-dialog-wrap" :class="{active: visible}">
    <div class="m-dialog">
      <div class="m-dialog-title">{{title}}</div>
      <div class="m-dialog-content">
        <slot></slot>
      </div>
      <div class="m-dialog-footer">
        <slot name="footer"></slot>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: ['visible', 'title']
}
</script>

<style>

</style>

// demo/react/m-app/src/components/Dialog.js
import React from 'react'

const Dialog = (props) => {
  let { visible, title } = props
  return (
    <div className={"m-dialog-wrap " + (visible ? 'active' : '')}>
      <div className="m-dialog">
        <div className="m-dialog-header">{title}</div>
        <div className="m-dialog-content"></div>
        <div className="m-dialog-footer">
          <button className="m-btn" onClick={props.onCancel}>取消</button>
          <button className="m-btn">确定</button>
        </div>
      </div>
    </div>
  )
}

export default Dialog
