// demo/vue/m-app-vue3/src/components/light/Dialog.vue
<template>
  <div :class="[`m-mask ${visible ? 'active' : ''}`]">
    <div class="m-dialog">
      <div class="m-dialog-header">
        <span class="m-dialog-header-title">{{title}}</span>
        <span class="m-dialog-header-close" @click="handleClose">X</span>
      </div>
      <div class="m-dialog-content">
        <slot name="content"></slot>
      </div>
      <div class="m-dialog-footer">
        <button class="m-btn" @click="handleOk">确定</button>
        <button class="m-btn" @click="handleClose">取消</button>
      </div>
    </div>
  </div>
</template>
 
<script>
 
export default {
  props: {
    visible: {
      type: Boolean
    },
    title: {
      type: String
    }
  },
  emits: ['onClose', 'onOk'],
  setup(props, context) {
 
    const handleClose = () => {
      context.emit('onClose')
    }
 
    const handleOk = () => {
      context.emit('onOk')
    }
 
    return {
      handleClose,
      handleOk
    }
  }
}
</script>
 
<style>
 
</style>

// demo/react/m-app/src/components/Dialog.js
import React from 'react'
import Icon from './Icon'

const Dialog = (props) => {
  let { visible, title, children } = props
  return (
    <div className={"m-dialog-wrap " + (visible ? 'active' : '')}>
      <div className="m-dialog">
        <div className="m-dialog-header">
          <div className="m-dialog-title" >{title}</div>
          <Icon name="guanbi" className="m-dialog-close" onClick={props.onCancel}></Icon>
        </div>
        <div className="m-dialog-content">
          {children}
        </div>
        <div className="m-dialog-footer">
          <button className="m-btn" onClick={props.onCancel}>取消</button>
          <button className="m-btn" onClick={props.onOk}>确定</button>
        </div>
      </div>
    </div>
  )
}

export default Dialog
