// demo/vue/m-app-vue3/src/components/light/Footer.vue
<template>
  <div class="m-footer">
    <router-link to="/index/home" class="m-footer-item">
      <Icon name="home" class="m-footer-icon" />
      <div class="m-footer-text">首页</div>
    </router-link>
    <router-link to="/index/my_books" class="m-footer-item">
      <Icon name="shubao" class="m-footer-icon" />
      <div class="m-footer-text">书包</div>
    </router-link>
    <router-link to="/index/me" class="m-footer-item">
      <Icon name="me" class="m-footer-icon" />
      <div class="m-footer-text">我的</div>
    </router-link>        
  </div>
</template>

<script>
import Icon from './Icon'

export default {
  components: {
    Icon
  }
}
</script>

<style>

</style>

// demo/react/m-app/src/components/Footer.js
import React from 'react'
import { NavLink } from 'react-router-dom'
import Icon from './Icon'

const Footer = () => {
  return (
    <div className="m-footer">
      <NavLink to="/index/home" className="m-footer-item">
        <Icon name="shouye" className="m-footer-icon"></Icon>
        <div className="m-footer-text">首页</div>
      </NavLink>
      <NavLink to="/index/my_books" className="m-footer-item">
        <Icon name="shubao" className="m-footer-icon"></Icon>
        <div className="m-footer-text">书包</div>
      </NavLink>
      <NavLink to="/index/me" className="m-footer-item">
        <Icon name="wodedangxuan" className="m-footer-icon"></Icon>
        <div className="m-footer-text">我的</div>
      </NavLink>
    </div>
  )
}

export default Footer
