// demo/vue/m-app2/src/components/List.vue
<template>
  <div class="m-list" @scroll="handleScroll">
    <div v-for="categroy in list" :key="categroy.id" :id="categroy.id" class="m-category js-category">
      <div class="m-category-title">{{categroy.title}}</div>
      <div v-for="book in categroy.list" :key="book.id" class="m-list-item">
        <div class="m-list-img-wrap">
          <img :src="book.avatar" class="m-list-img" >
        </div>
        <div class="m-info">
          {{book.title}}
          <Stars :count="book.stars"></Stars>
          <button @click="handleVisible(book)">添加</button>
        </div>
      </div>
    </div>
    <Dialog 
      :visible="visible"
      title="添加"
      @onCancel="handleCancel" 
      @onOk="handleOk" >
      <template v-slot:content>
        <div class="m-add-wrap">
          <div class="m-add-info">
            <button class="m-btn" @click="handleSub">减</button>
            <input type="text" :value="book.count" placeholder="数量" class="m-input" @input="handleInput">
            <button class="m-btn" @click="handleAdd" >加</button>
          </div>
        </div>
      </template>
    </Dialog>
  </div>
</template>

<script>
import Stars from './Stars'
import Dialog from './Dialog'
import Api from '../api'
let topArr = []

export default {
  data() {
    return {
      visible: false,
      book: {}
    }
  },
  computed: {
    list() {
      return this.$store.state.list
    }
  },
  components: {
    Stars,
    Dialog
  },
  methods: {
    handleScroll(e) {
      let { scrollTop } = e.target
      scrollTop = scrollTop + 40
      if (this.$store.state.isRealScroll) {
        for (let i = 0; i < topArr.length - 1; i++) {
          if (topArr[i] < scrollTop && scrollTop < topArr[i + 1]) {
            this.$store.commit({ type: 'setState', key: 'currentId', value: i })
          }
        }
      }
    },
    handleVisible(book) {
      this.visible = true
      book.count = 1
      this.book = book
    },
    handleCancel() {
      this.visible = false
    },
    handleOk() {
      this.handleCancel()
      let myBooks = this.$store.state.myBooks
      let index = myBooks.findIndex(item => item.id === this.book.id)
      if (index >= 0) {
        myBooks[index].checked = true
        myBooks[index].count += this.book.count
      } else {
        this.book.checked = true
        myBooks.push({...this.book})
      }
      
      this.$store.commit({ type: 'setState', key: 'myBooks', value: myBooks })
      Api.myBooks({ book: this.book }, 'post')
    },
    handleAdd() {
      this.book.count++
      this.book = { ...this.book }
    },
    handleSub() {
      if (this.book.count > 1) {
        this.book.count--
        this.book = { ...this.book }
      }
    },
    handleInput(e) {
      this.book.count = e.target.value.replace(/[^\d]/g, '') - 0
      this.book = { ...this.book }
    }
  },
  updated() {
    topArr = Array.from(document.getElementsByClassName('js-category')).map(item => item.offsetTop)
    topArr.push(Infinity)
  }
}
</script>

<style>

</style>

// demo/react/m-app/src/components/List.js
import React, { useState, useEffect } from 'react'
import { connect } from 'react-redux'
import LazyLoad from 'react-lazy-load'
import Stars from './Stars'
import Dialog from './Dialog'
import actionCreator from '../store/actionCreator'

let topArr = []
const List = (props) => {
  let { list, isRealScroll } = props
  let [ visible, setVisible ] = useState(false)
  let [ book, setBook ] = useState({count: 1})

  const handleScroll = (e) => {
    let scrollTop = e.target.scrollTop + 40
    if (isRealScroll) {
      for (let i = 0; i < topArr.length - 1; i++) {
        if (topArr[i] <= scrollTop && scrollTop < topArr[i + 1]) {
          props.onSetState(['currentId'], i)
        }
      }
    }
  }

  const handleShowDialog = (book) => {
    book.count = 1
    setBook(book)
    setVisible(true)
  }

  const handleInput = (e) => {
    let count = e.target.value.replace(/[^\d]/g, '') - 0
    if (count === 0) {
      count = 1
    }
    book.count = count
    setBook({...book})
  }

  const handleAdd = () => {
    book.count++
    setBook({...book})
  }

  const handleSub = () => {
    if (book.count > 1) {
      book.count--
      setBook({...book})
    }
  }

  const handleCancel = () => {
    setVisible(false)
  }

  const handleAddToMyBooks = () => {
    book.checked = true
    props.onDispatch(actionCreator.myBooks({book}, 'post', handleCancel))
  }

  useEffect(() => {
    topArr = Array.from(document.getElementsByClassName('js-category')).map(item => item.offsetTop)
    topArr.push(Infinity)
  }, [props])


  let listDom = list.map(category => (
    <div key={category.id} id={category.id} className="js-category">
      <div className="m-list-category-title">{category.title}</div>
      {
        category.list.map(book => (
          <div key={book.id} className="m-list-item">
            <LazyLoad className="m-list-img-wrap">
              <img src={book.avatar} className="m-list-img"></img>
            </LazyLoad>
            <div className="m-list-info">
              {book.title}
              <Stars count={book.stars}></Stars>
              <button onClick={() => handleShowDialog(book)}>添加</button>
            </div>
          </div>
        ))
      }
    </div>
  ))
  return (
    <div className="m-list" onScroll={(e) => handleScroll(e)}>
      {listDom}
      <Dialog visible={visible} title="添加" onCancel={() => handleCancel()} onOk={() => handleAddToMyBooks()} >
        <div className="m-add-info-wrap">
          <div className="m-add-info">
            <button className="m-btn" onClick={() => handleSub()}>-</button>
            <input value={book.count} placeholder="数量" className="m-input" onChange={(e) => handleInput(e)} ></input>
            <button className="m-btn" onClick={() => handleAdd()} >+</button>
          </div>
        </div>
      </Dialog>
    </div>
  )
}

const mapStateToProps = (state) => {
  return {
    list: state.getIn(['list']).toJS(),
    isRealScroll: state.getIn(['isRealScroll'])
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    onSetState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    onDispatch(action) {
      dispatch(action)
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(List)
