// m-app-1708E/react/m-app-test/src/components/List.js
import React, { Component } from 'react'
import { connect } from 'react-redux'

let offsetTopArr = []
class List extends Component {
  handleScroll(e) {
    let { isRealScroll } = this.props
    let { scrollTop } = e.target
    //console.log(scrollTop)
    scrollTop = scrollTop + 50
    if (isRealScroll) {
      for (let i = 0; i < offsetTopArr.length; i++) {
        if (offsetTopArr[i] < scrollTop && scrollTop < offsetTopArr[i + 1]) {
          console.log(i)
          this.props.onSetState(['currentId'], i)
        }
      }
    }
  }

  componentDidUpdate() {
    offsetTopArr = Array.from(document.getElementsByClassName('js-category-item')).map(item => item.offsetTop)
    offsetTopArr.push(Infinity)
    console.log(offsetTopArr)
  }

  render() {
    let { listAll } = this.props

    let listDom = listAll.map(category => (
      <div key={category.id} className="m-category-item js-category-item" id={category.id}>
        <div className="m-category-title">{category.title}</div>
        {
          category.list.map(book => (
            <div key={book.id} className="m-list-item">
              <div className="m-list-img-wrap">
                <img src={book.avatar} className="m-list-img" alt={book.title}></img>
              </div>
              <div className="m-list-info">{book.title}</div>
            </div>
          ))
        }
      </div>
    ))

    return (
      <div className="m-list" onScroll={(e) => { this. handleScroll(e)}}>
        {listDom}
      </div>
    )
  }
}

//从仓库里取值，相当于使用vuex时，组件里使用computed取仓库里的值
const mapStateToProps = (state) => {
  return {
    listAll: state.getIn(['listAll']).toJS(),
    currentId:state.getIn(['currentId']),
    isRealScroll: state.getIn(['isRealScroll'])
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    //同步，相当于vuex里提交mutation
    onSetState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    //异步，相当于vuex里提交action
    onDispatch(action) {
      dispatch(action)
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(List)

// demo/ts/vue/m-app/src/components/List.vue
<template>
  <div class="m-list" @scroll="handleScoll">
    <div v-for="category in list" :key="category.id" :id="category.id" class="js-list-item">
      <div class="m-category-title">{{category.title}}</div>
      <div v-for="book in category.list" :key="book.id" class="m-list-item">
        <div class="m-list-img-wrap">
          <img :src="book.avatar" class="m-list-img">
        </div>
        <div class="m-list-info">
          <div>{{book.title}}</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { Vue, Component } from 'vue-property-decorator'
import { State, Mutation } from 'vuex-class'

let topArr = []

@Component
export default class List extends Vue {
  @State(state => state.list) list
  @State(state => state.isRealScroll) isRealScroll
  @Mutation('setState') setState

  handleScoll(e) {
    let { scrollTop } = e.target
    scrollTop = scrollTop + 40
    if (this.isRealScroll) {
      for (let i = 0; i < topArr.length - 1; i++) {
        if (topArr[i] < scrollTop && scrollTop < topArr[i + 1]) {
          this.setState({ key: 'currentId', value: i })
        }
      }
    }    
  }

  updated() {
    topArr = Array.from(document.getElementsByClassName('js-list-item')).map(item => item.offsetTop)
    topArr.push(Infinity)
    console.log(topArr)
  }
}
</script>

<style>

</style>
