// m-app-1708E/react/m-app-test2/src/components/Footer.js
import React from 'react'
import { NavLink } from 'react-router-dom'
import Icon from './Icon'

const Footer = () => {
  return (
    <div className="m-footer">
      <NavLink to="/index/home" className="m-footer-item">
        <Icon type="shouye" className="m-footer-item-icon" ></Icon>
        <div className="m-footer-item-text">首页</div>
      </NavLink>
      <NavLink to="/index/my_book" className="m-footer-item">
        <Icon type="shubao" className="m-footer-item-icon" ></Icon>
        <div className="m-footer-item-text">书包</div>
      </NavLink>
      <NavLink to="/index/me" className="m-footer-item">
        <Icon type="wode" className="m-footer-item-icon" ></Icon>
        <div className="m-footer-item-text">我的</div>        
      </NavLink>
    </div>
  )
}

export default Footer

// demo/vue/m-app-test2/src/components/Footer.vue
<template>
  <div class="m-footer">
    <router-link to="/index/home" class="m-footer-item">
      <Icon type="home" class="m-footer-icon"></Icon>
      <div class="m-footer-text">首页</div>
    </router-link>
    <router-link to="/index/my_book" class="m-footer-item">
      <Icon type="shubao" class="m-footer-icon"></Icon>
      <div class="m-footer-text">书包</div>
    </router-link>
    <router-link to="/index/me" class="m-footer-item">
      <Icon type="me" class="m-footer-icon"></Icon>
      <div class="m-footer-text">我的</div>
    </router-link>        
  </div>
</template>

<script>
import Icon from '../components/Icon'

export default {
  components: {
    Icon
  }
}
</script>

<style>

</style>
