// demo/ts/vue/m-app/src/components/Header.vue
<template>
  <div class="m-header">
    {{title1}}
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { State } from 'vuex-class'

@Component
export default class Header extends Vue {
  @State('title') title
  @State(state => {
    return state.title
  }) title1
}
</script>

<style>

</style>

// m-app-1708E/react/m-app/src/components/Header.js
import React, { Component } from 'react'
import { connect } from 'react-redux'

class Header extends Component {
  render() {
    let { title } = this.props
    return (
      <div className="m-header">
        {title}
      </div>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    title: state.getIn(['title'])
  }
}

export default connect(mapStateToProps)(Header)
