// demo/react/m-app-test/src/views/Index.js
import React from 'react'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { Switch, Route } from 'react-router-dom'
import Home from './Home'
import MyBooks from './MyBooks'
import Me from './Me'

const Index = () => {
  return (
    <div className="m-wrap">
      <Header></Header>
      <Switch>
        <Route path="/index/home" component={Home}></Route>
        <Route path="/index/my_books" component={MyBooks}></Route>
        <Route path="/index/me" component={Me}></Route>
      </Switch>
      <Footer></Footer>
    </div>
  )
}

export default Index

// demo/vue/m-app-test2/src/views/Index.vue
<template>
  <div class="m-index">
    <Header></Header>
    <router-view></router-view>
    <Footer></Footer>
  </div>
</template>

<script>
import Header from '../components/Header'
import Footer from '../components/Footer'

export default {
  components: {
    Header,
    Footer
  }
}
</script>

<style>

</style>
