// m-app-1707B/书包/src/views/Detail.vue
<template>
  <div>
    <img :src="detail.avatar">
  </div>
</template>

<script>
import axios from 'axios'

export default {
  data() {
    return {
      detail: {}
    }
  },
  mounted() {
    let { id } = this.$route.params
    axios({
      url: `/api/detail?id=${id}`
    }).then(res => {
      if (res.data.code === 200) {
        this.detail = res.data.data
      }
    })
  }
}
</script>

<style>

</style>

// demo/react/m-app/src/views/Detail.js
import React, { useState, useEffect } from 'react'
import Api from '../api'

const Detail = (props) => {
  const [ detail, setDetail ] = useState({count: 1})

  useEffect(() => {
    let { id } = props.match.params
    Api.detail(id).then(res => {
      if (res.code === 200) {
        setDetail(res.data)
      }
    })
  }, [])
  return (
    <div>
      <div className="m-detail-img-wrap">
        <img src={detail.avatar}></img>
      </div>
    </div>
  )
}

export default Detail
