// demo/vue/m-app2/src/views/Detail.vue
<template>
  <div>
    <DetailHeader :title="detail.title"></DetailHeader>
    <div class="m-detail-img-wrap">
      <img :src="detail.avatar" >
    </div>
    
  </div>
</template>

<script>
import DetailHeader from '../components/DetailHeader'
import Api from '../api'

export default {
  data() {
    return {
      detail: {}
    }
  },
  components: {
    DetailHeader
  },
  mounted() {
    let { id } = this.$route.params
    Api.detail(id).then(res => {
      if (res.code === 200) {
        this.detail = res.data
      }
    })
  }
}
</script>

<style>

</style>

// demo/react/m-app/src/views/Detail.js
import React, { useState, useEffect } from 'react'
import Api from '../api'

const Detail = (props) => {
  const [ detail, setDetail ] = useState({count: 1})

  useEffect(() => {
    let { id } = props.match.params
    Api.detail(id).then(res => {
      if (res.code === 200) {
        setDetail(res.data)
      }
    })
  }, [])
  return (
    <div>
      <div className="m-detail-img-wrap">
        <img src={detail.avatar}></img>
      </div>
    </div>
  )
}

export default Detail
