// m-app-1708E/m-app-test/src/views/Login.vue
<template>
  <div>
    <div>
      <input v-model="username" placeholder="请输入用户名" autofocus>
    </div>
    <div>
      <input v-model="password" placeholder="请输入密码" :type="visible ? 'text' : 'password'" @keyup.enter="handleLogin">
      <Icon classname="m-login-icon" :type="visible ? 'xianshimima' :'buxianshimima'" @onClick="handleShow"></Icon>
    </div>
    <button @click="handleLogin">登录</button>
  </div>
</template>

<script>
import Api from '../api'
import Icon from '../components/Icon'

export default {
  data() {
    return {
      username: 'admin',
      password: '123456',
      visible: false
    }
  },
  components: {
    Icon
  },
  methods:{
    handleLogin() {
      if (this.username.trim() === '') {
        alert('用户名不能为空')
        return
      }
      if (this.password.trim() === '') {
        alert('密码不能为空')
        return
      }
      Api.login({username: this.username, password: this.password }).then(res => {
        if (res.code === 200) {
          localStorage.setItem('username', res.data.username)
          this.$router.push('/index/home')
        }
      })
    },
    handleShow() {
      this.visible = !this.visible
    }
  }
}
</script>

<style>

</style>

// demo/react/m-app/src/views/Login.js
import React, { useState } from 'react'
import Icon from '../components/Icon'
import Api from '../api'

const Login = (props) => {
  const [ username, setUsername ] = useState('admin')
  const [ password, setPassword ] = useState('123456') 
  const [ visible, setVisible ] = useState(false)

  const handleVisible = () => {
    setVisible(!visible)
  }

  const handleEnter = (e) => {
    if (e.keyCode === 13) {
      handleLogin()
    }
  }

  const handleLogin = () => {
    Api.login({ username, password }).then(res => {
      if (res.code === 200) {
        props.history.push('/index/home')
      }
    })
  }

  return (
    <div>
      <div>
        <input placeholder="请输入用户名" value={username} onChange={ (e) => setUsername(e.target.value) } autoFocus ></input>
      </div>
      <div>
        <input placeholder="请输入密码" value={password} onChange={ (e) => setPassword(e.target.value) } type={ visible ? "text" : "password"} onKeyUp={(e) => handleEnter(e)} ></input>
        <Icon name={ visible ? "xianshimima" : 'buxianshimima'} className="m-login-icon" onClick={() => handleVisible()} ></Icon>
      </div>
      <button onClick={() => handleLogin()}>登录</button>
    </div>
  )
}

export default Login
