// demo/vue/m-app2/src/components/Badge.vue
<template>
  <div class="m-badge-wrap">
    <slot></slot>
    <span class="m-badge" v-if="formatCount > 0 || typeof formatCount === 'string'" >{{formatCount}}</span>
  </div>
</template>

<script>
export default {
  props: {
    count: {
      type: Number
    }
  },
  computed: {
    formatCount() {
      if (this.count < 100) {
        return this.count
      } else {
        return '99+'
      }
    }
  }
}
</script>

<style>

</style>

// demo/react/m-app-test/src/components/Badge.js
import React, { Component } from 'react'

export default class Badge extends Component {
  render() {
    let { children, count } = this.props
    if (count > 99) {
      count = '99+'
    }
    return (
      <span className="m-badge-wrap">
        {children}
        { (typeof count === 'string' || count > 0) && <span className="m-badge">{count}</span>}
      </span>
    )
  }
}
