// demo/vue/m-app2/src/components/DetailHeader.vue
<template>
  <div class="m-detail-header">
    <Icon name="flow" class="m-detail-header-icon" @onClick="handleBack"></Icon>
    <div class="m-detail-header-title">{{title}}</div>
    <Icon name="gengduo" class="m-detail-header-icon"></Icon>
  </div>
</template>

<script>
import Icon from './Icon'

export default {
  props: {
    title: {
      type: String
    }
  },
  components: {
    Icon
  },
  methods: {
    handleBack() {
      this.$router.go(-1)
    }
  }
}
</script>

<style>

</style>

// demo/react/m-app-test/src/components/DetailHeader.js
import React, { Component } from 'react'
import { withRouter } from 'react-router-dom'
import Icon from './Icon'

class DetailHeader extends Component {

  handleBack() {
    this.props.history.go(-1)
  }

  render() {
    let { title } = this.props
    return (
      <div className="m-detail-header">
        <Icon name="flow" className="m-detail-header-icon" onClick={() => this.handleBack()}></Icon>
        <div className="m-detail-header-info">{title}</div>
        <Icon name="iconzhengli_fenxiang" className="m-detail-header-icon"></Icon>
        <Icon name="gengduo" className="m-detail-header-icon"></Icon>
      </div>
    )
  }
}

export default withRouter(DetailHeader)
