// m-app-1707A/react/m-book-test/src/components/Sidebar.js
import React, { Component } from 'react'
import { connect } from 'react-redux'
import actionCreator from '../store/actionCreator'

let timer
class Sidebar extends Component {
  handleNav(id, e) {
    this.props.onSetState(['currentId'], id)
    this.props.onSetState(['isRealScroll'], false)
    clearTimeout(timer)
    timer = setTimeout(() => {
      this.props.onSetState(['isRealScroll'], true)
    }, 1000);
    document.getElementById(id).scrollIntoView({block: 'start', behavior: 'smooth'})
  }
  componentDidMount() {
    this.props.onDispatch(actionCreator.getListAll())
  }
  render() {
    let { listAll, currentId } = this.props
    let listAllDom = listAll.map(item => (
      <a 
        key={item.id} 
        // href={'#' + item.id}
        onClick={this.handleNav.bind(this, item.id)}
        className={"m-sidebar-item " + (currentId === item.id ? 'active' : '')}>
        {item.title}
      </a>
    ))
    return (
      <div className="m-sidebar">
        {listAllDom}
      </div>
    )
  }
}


const mapStateToProps = (state) => {
  state = state.toJS()
  return {
    listAll: state.listAll,
    currentId: state.currentId
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    onSetState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    onDispatch(action) {
      dispatch(action)
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(Sidebar)

// demo/vue/m-app2/src/components/Sidebar.vue
<template>
  <div class="m-sidebar">
    <div 
      v-for="item in list" 
      :key="item.id" 
      class="m-sidebar-item" 
      :class="currentId === item.id ? 'active' : ''"
      @click="handleNav(item.id)">{{item.title}}</div>
  </div>
</template>

<script>
let timer

export default {
  computed: {
    list() {
      return this.$store.state.list
    },
    currentId() {
      return this.$store.state.currentId
    }
  },
  methods: {
    handleNav(id) {
      this.$store.commit({ type: 'setState', key: 'currentId', value: id })
      document.getElementById(id).scrollIntoView({ block: 'start', behavior: 'smooth' })
      clearTimeout(timer)
      this.$store.commit({ type: 'setState', key: 'isRealScroll', value: false })
      timer = setTimeout(() => {
        this.$store.commit({ type: 'setState', key: 'isRealScroll', value: true })
      }, 1000)
    }
  }
}
</script>

<style>

</style>
