// demo/react/m-app-test/src/components/Stars.js
import React, { Component } from 'react'
import Icon from './Icon'

export default class Stars extends Component {
  render() {
    let { count } = this.props
    let arr = []
    for (let i = 0; i < 5; i++) {
      arr.push(<Icon name="xingxing" className={'m-star ' + (i < count ? 'active' : '')}></Icon>)
    }
    return (
      <div>
        {
          arr
        }
      </div>
    )
  }
}

// demo/vue/m-app2/src/components/Stars.vue
<template>
  <div class="m-stars-wrap">
    <Icon name="xingxing" v-for="n in 5" :key="n" :class="[ 'm-star ' + (n <= count && 'active') ]"></Icon>
  </div>
</template>

<script>
import Icon from './Icon'

export default {
  props: {
    count: {
      type: Number
    }
  },
  components: {
    Icon
  }
}
</script>

<style>

</style>
