// demo/react/m-app/src/components/Stars.js
import React from 'react'
import Icon from './Icon'

const Stars = (props) => {
  let { count } = props

  let starsDom = []
  for (let i = 0; i < 5; i++) {
    starsDom.push(<Icon name="xingxing" key={i} className={"m-star-item " + (i < count ? 'active' : '') }></Icon>)
  }

  return (
    <div>
      {starsDom}
    </div>
  )
}

export default Stars

// demo/vue/m-app2/src/components/Stars.vue
<template>
  <div class="m-stars-wrap">
    <Icon name="xingxing" v-for="n in 5" :key="n" :class="[ 'm-star ' + (n <= count && 'active') ]"></Icon>
  </div>
</template>

<script>
import Icon from './Icon'

export default {
  props: {
    count: {
      type: Number
    }
  },
  components: {
    Icon
  }
}
</script>

<style>

</style>
