// demo/react/m-app/src/views/Login.js
import React, { useState } from 'react'
import Icon from '../components/Icon'
import Api from '../api'

const Login = (props) => {
  const [ username, setUsername ] = useState('admin')
  const [ password, setPassword ] = useState('123456') 
  const [ visible, setVisible ] = useState(false)

  const handleVisible = () => {
    setVisible(!visible)
  }

  const handleEnter = (e) => {
    if (e.keyCode === 13) {
      handleLogin()
    }
  }

  const handleLogin = () => {
    Api.login({ username, password }).then(res => {
      if (res.code === 200) {
        props.history.push('/index/home')
      }
    })
  }

  return (
    <div>
      <div>
        <input placeholder="请输入用户名" value={username} onChange={ (e) => setUsername(e.target.value) } autoFocus ></input>
      </div>
      <div>
        <input placeholder="请输入密码" value={password} onChange={ (e) => setPassword(e.target.value) } type={ visible ? "text" : "password"} onKeyUp={(e) => handleEnter(e)} ></input>
        <Icon name={ visible ? "xianshimima" : 'buxianshimima'} className="m-login-icon" onClick={() => handleVisible()} ></Icon>
      </div>
      <button onClick={() => handleLogin()}>登录</button>
    </div>
  )
}

export default Login

// m-app-1707B/书包/前端/src/views/Login.vue
<template>
  <div>
    <div>
      <input type="text" v-model="username" placeholder="请输入用户名" />
    </div>
    <div>
      <input :type="show ? 'text' : 'password'" v-model="password" placeholder="请输入密码" />
      <Icon :type="show ? 'xianshimima' : 'guanbi'" @click.native="handleShow"></Icon>
    </div>
    <button @click="handleLogin">登录</button>
  </div>
</template>

<script>
import Api from "../api";
import Icon from '../components/Icon'

export default {
  data() {
    return {
      username: "admin",
      password: "123456",
      show: false
    };
  },
  components: {
    Icon
  },
  methods: {
    handleLogin() {
      Api.login({
        username: this.username,
        password: this.password
      }).then(res => {
        if (res.code === 200) {
          this.$router.push("/index/home");
        } else {
          alert(res.message);
        }
      });
    },
    handleShow() {
      this.show = !this.show
    }
  }
};
</script>

<style>
</style>
