// m-app-1707B/react/m-book-test/src/views/Index.js
import React, { Component } from 'react'
import { Switch, Route } from 'react-router-dom'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Home from './Home'
import MyBook from './MyBook'
import Me from './Me'

export default class Index extends Component {
  render() {
    return (
      <div className="m-wrap">
        <Header></Header>
        <Switch>
          <Route path="/index/home" component={Home}></Route>
          <Route path="/index/my_book" component={MyBook}></Route>
          <Route path="/index/me" component={Me}></Route>
        </Switch>
        <Footer></Footer>
      </div>
    )
  }
}

// demo/ts/vue/m-app-tslint/src/views/Index.vue
<template>
  <div class="m-wrap">
    <Header></Header>
    <router-view></router-view>
    <Footer></Footer>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import Header from '../components/Header.vue'
import Footer from '../components/Footer.vue'

@Component({
  components: {
    Header,
    Footer
  }
})
export default class Index extends Vue {
  
}
</script>

<style>

</style>
