// demo/react/m-app/src/components/Badge.js
import React from 'react'

const Badge = (props) => {
  let { count, children } = props
  if (count > 99) {
    count = '99+'
  }
  return (
    <span className="m-badge-wrap">
      { (typeof count === 'string' || count > 0) && <span className="m-badge">{count}</span>}
      {children}
    </span>
  )
}

export default Badge

// demo/ts/vue/m-app-tslint/src/components/Badge.vue
<template>
  <span class="m-badge-wrap">
    <slot></slot>
    <span class="m-badge" v-if="formatCount > 0 || typeof formatCount === 'string'">{{formatCount}}</span>
  </span>
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator'

@Component
export default class Badge extends Vue {
  @Prop() count!:number

  get formatCount() {
    if (this.count < 100) {
      return this.count
    } else if (this.count >= 100) {
      return '99+'
    } else {
      return 0
    }
  }
}
</script>

<style>

</style>
