// demo/ts/react/react-ts-app/src/components/DetailHeader.tsx
import React from 'react'
import { withRouter, RouteComponentProps } from 'react-router-dom'
import Icon from './Icon'

interface IProp extends RouteComponentProps {
  title: string
}

const DetailHeader = (props: IProp) => {
  let { title } = props

  const handleBack = () => {
    props.history.go(-1)
  }

  return (
    <div className="m-detail-header">
      <Icon name="back" className="m-detail-header-icon" onClick={() => handleBack()}></Icon>
      <div className="m-detail-header-info">{title}</div>
      <Icon name="fenxiang" className="m-detail-header-icon"></Icon>
      <Icon name="more" className="m-detail-header-icon"></Icon>
    </div>
  )
}

export default withRouter(DetailHeader)

// demo/ts/vue/m-app-tslint/src/components/DetailHeader.vue
<template>
  <div class="m-detail-header">
    <Icon name="back" class="m-detail-header-icon" @onClick="handleBack"></Icon>
    <div class="m-detail-header-title">{{title}}</div>
    <Icon name="more" class="m-detail-header-icon"></Icon>
  </div>
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator'
import Icon from './Icon.vue'

@Component({
  components: {
    Icon
  }
})
export default class DetailHeader extends Vue {
  @Prop() title!: string

  handleBack() {
    (this as any).$router.go(-1)
  }
}
</script>
