// demo/react/m-app/src/components/List.js
import React, { useState, useEffect } from 'react'
import { connect } from 'react-redux'
import LazyLoad from 'react-lazy-load'
import { withRouter } from 'react-router-dom'
import Stars from './Stars'
import Dialog from './Dialog'
import actionCreator from '../store/actionCreator'

let topArr = []
const List = (props) => {
  let { list, isRealScroll } = props
  let [ visible, setVisible ] = useState(false)
  let [ book, setBook ] = useState({count: 1})

  const handleScroll = (e) => {
    let scrollTop = e.target.scrollTop + 40
    if (isRealScroll) {
      for (let i = 0; i < topArr.length - 1; i++) {
        if (topArr[i] <= scrollTop && scrollTop < topArr[i + 1]) {
          props.onSetState(['currentId'], i)
        }
      }
    }
  }

  const handleShowDialog = (book) => {
    book.count = 1
    setBook(book)
    setVisible(true)
  }

  const handleInput = (e) => {
    let count = e.target.value.replace(/[^\d]/g, '') - 0
    if (count === 0) {
      count = 1
    }
    book.count = count
    setBook({...book})
  }

  const handleAdd = () => {
    book.count++
    setBook({...book})
  }

  const handleSub = () => {
    if (book.count > 1) {
      book.count--
      setBook({...book})
    }
  }

  const handleCancel = () => {
    setVisible(false)
  }

  const handleAddToMyBooks = () => {
    book.checked = true
    props.onDispatch(actionCreator.myBooks({book}, 'post', handleCancel))
  }

  const handleDetail = (id) => {
    props.history.push(`/detail/${id}`)
  } 

  useEffect(() => {
    topArr = Array.from(document.getElementsByClassName('js-category')).map(item => item.offsetTop)
    topArr.push(Infinity)
  }, [props])


  let listDom = list.map(category => (
    <div key={category.id} id={category.id} className="js-category">
      <div className="m-list-category-title">{category.title}</div>
      {
        category.list.map(book => (
          <div key={book.id} className="m-list-item">
            <LazyLoad className="m-list-img-wrap">
              <img src={book.avatar} className="m-list-img" onClick={() => handleDetail(book.id)}></img>
            </LazyLoad>
            <div className="m-list-info">
              {book.title}
              <Stars count={book.stars}></Stars>
              <button onClick={() => handleShowDialog(book)}>添加</button>
            </div>
          </div>
        ))
      }
    </div>
  ))
  return (
    <div className="m-list" onScroll={(e) => handleScroll(e)}>
      {listDom}
      <Dialog visible={visible} title="添加" onCancel={() => handleCancel()} onOk={() => handleAddToMyBooks()} >
        <div className="m-add-info-wrap">
          <div className="m-add-info">
            <button className="m-btn" onClick={() => handleSub()}>-</button>
            <input value={book.count} placeholder="数量" className="m-input" onChange={(e) => handleInput(e)} ></input>
            <button className="m-btn" onClick={() => handleAdd()} >+</button>
          </div>
        </div>
      </Dialog>
    </div>
  )
}

const mapStateToProps = (state) => {
  return {
    list: state.getIn(['list']).toJS(),
    isRealScroll: state.getIn(['isRealScroll'])
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    onSetState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    onDispatch(action) {
      dispatch(action)
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(List))

// demo/ts/vue/m-app-tslint/src/components/List.vue
<template>
  <div class="m-list" @scroll="handleScoll">
    <div v-for="category in list" :key="category.id" :id="category.id" class="js-list-item">
      <div class="m-category-title">{{category.title}}</div>
      <div v-for="book in category.list" :key="book.id" class="m-list-item" @click="handleDetail(book.id)">
        <div class="m-img-wrap">
          <img v-lazy="book.avatar" class="m-img">
        </div>
        <div class="m-list-info">
          <div>{{book.title}}</div>
          <Stars :count="book.stars"></Stars>
          <button @click.stop="handleShowDialog(book)">添加</button>
        </div>
      </div>
    </div>
    <Dialog title="添加" :visible="visible" @onCancel="handleCancel" @onOk="handleAddToMyBooks">
      <template v-slot:content>
        <div class="m-add-wrap">
          <div class="m-add-info">
            <button class="m-btn" @click="handleSub">减</button>
            <input type="text" :value="book.count" placeholder="数量" class="m-input" @input="handleInput">
            <button class="m-btn" @click="handleAdd" >加</button>
          </div>
        </div>
      </template>
    </Dialog>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { State, Mutation, Action } from 'vuex-class'
import Stars from './Stars.vue'
import Dialog from './Dialog.vue'
import Api from '../api'

let topArr:number[] = []

@Component({
  components: {
    Stars,
    Dialog
  }
})
export default class List extends Vue {
  @State(state => state.list) list!:any[]
  @State(state => state.isRealScroll) isRealScroll!:boolean
  @Mutation('setState') setState!:Function
  @Action('myBooksAction') myBooksAction!:Function

  visible = false
  book:any = { count: 1 }

  handleScoll(e:any) {
    let scrollTop = e.target.scrollTop
    scrollTop = scrollTop + 40
    if (this.isRealScroll) {
      for (let i = 0; i < topArr.length - 1; i++) {
        if (topArr[i] < scrollTop && scrollTop < topArr[i + 1]) {
          this.setState({ key: 'currentId', value: i })
        }
      }
    }    
  }

  handleShowDialog(book:any) {
    this.visible = true
    book.count = 1
    this.book = book
  }

  handleCancel() {
    this.visible = false
  }

  handleAddToMyBooks() {
    this.book.checked = true
    this.myBooksAction({ data: { book: this.book}, method: 'post', callback: this.handleCancel })
  }

  handleAdd() {
    this.book.count++
    this.book = { ...this.book }
  }  

  handleSub() {
    if (this.book.count > 1) {
      this.book.count--
      this.book = { ...this.book }
    }
  }
  
  handleInput(e:any) {
    let count = e.target.value.replace(/[^\d]/g, '') - 0
    if (count === 0) {
      count = 1
    }
    this.book.count = count
    this.book = { ...this.book }
  }

  handleDetail(id:number) {
    (this as any).$router.push(`/detail/${id}`)
  }

  updated() {
    topArr = Array.from(document.getElementsByClassName('js-list-item')).map((item:any) => item.offsetTop)
    topArr.push(Infinity)
    console.log(topArr)
  }
}
</script>

<style>

</style>
