// demo/react/m-app-test-plus/src/components/Sidebar.js
import React from 'react'
import { connect } from 'react-redux'

const Sidebar = (props) => {
  let { list, currentId } = props

  const handleNav = (id) => {
    props.onSetState(['currentId'], id)
    document.getElementById(id).scrollIntoView({ block: 'start', behavior: 'smooth' })
  }

  let listDom = list.map(item => (
    <div key={item.id} className={"m-sidebar-item " + (currentId === item.id ? 'active' : '')} onClick={() => handleNav(item.id)}>
      {item.title}
    </div>
  ))

  return (
    <div className="m-sidebar">
      {listDom}
    </div>
  )
}

//相当于vuex里计算属性，取值
const mapStateToProps = (state) => {
  return {
    list: state.getIn(['list']).toJS(),
    currentId: state.getIn(['currentId'])
  }
}

//相当于提交mutation，改值
const mapDispatchToProps = (dispatch) => {
  return {
    onSetState(key, value) {
      dispatch({type: 'SET_STATE', key, value})
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(Sidebar)

// demo/ts/vue/m-app-tslint/src/components/Sidebar.vue
<template>
  <div class="m-sidebar">
    <div v-for="item in list" :key="item.id" :class="[`m-sidebar-item ${currentId === item.id ? 'active' : '' }` ]" @click="handleNav(item.id)">
      {{item.title}}
    </div>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { State, Mutation } from 'vuex-class'

let timer: any

@Component
export default class Sidebar extends Vue {
  @State(state => state.list) list!:any[]
  @State(state => state.currentId) currentId!:number
  @Mutation('setState') setState!:any

  handleNav(id:number) {
    this.setState({ key: 'currentId', value: id });
    (document as any).getElementById(id + '').scrollIntoView({ block: 'start', behavior: 'smooth' })
    clearTimeout(timer)
    this.setState({ key: 'isRealScroll', value: false })
    timer = setTimeout(() => {
      this.setState({ key: 'isRealScroll', value: true })
    }, 1000)
  }
}
</script>

<style>

</style>
