// demo/ts/react/react-ts-app/src/components/Sidebar.tsx
import React, { Dispatch } from 'react'
import { connect } from 'react-redux'
import { IStore, IList } from '../types'

interface IProps {
  list: IList[],
  currentId: number,
  onSetState: (key: string, value: any) => void
  onDispatch: (action: Function) => void
}

let timer: any
const Sidebar = (props: IProps) => {
  const { list, currentId } = props

  const handleNav = (id: number) => {
    props.onSetState('currentId', id);
    props.onSetState('isRealScroll', false)
    //@ts-ignore
    document.getElementById(id + '').scrollIntoView({ block: 'start', behavior: 'smooth' })

    clearTimeout(timer)
    timer = setTimeout(() => {
      props.onSetState('isRealScroll', true)
    }, 1000)
  }

  const sidebarDom = list.map((item: IList) => (
    <div key={item.id} className={`m-sidebar-item ${currentId === item.id ? 'active' : ''}`} onClick={() => handleNav(item.id) }>{item.title}</div>
  ))

  return (
    <div className="m-sidebar">
      {sidebarDom}
    </div>
  )
}

const mapStateToProps = (state: IStore) => {
  return {
    list: state.book.list,
    currentId: state.book.currentId
  }
}

const mapDispatchToProps = (dispatch: Dispatch<any>) => {
  return {
    onSetState(key: string, value: any) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    onDispatch(action: Function) {
      dispatch(action)
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(Sidebar)

// demo/ts/vue/m-app-tslint/src/components/Sidebar.vue
<template>
  <div class="m-sidebar">
    <div v-for="item in list" :key="item.id" :class="[`m-sidebar-item ${currentId === item.id ? 'active' : '' }` ]" @click="handleNav(item.id)">
      {{item.title}}
    </div>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { State, Mutation } from 'vuex-class'

let timer: any

@Component
export default class Sidebar extends Vue {
  @State(state => state.list) list!:any[]
  @State(state => state.currentId) currentId!:number
  @Mutation('setState') setState!:Function

  handleNav(id:number) {
    this.setState({ key: 'currentId', value: id });
    //@ts-ignore
    document.getElementById(id + '').scrollIntoView({ block: 'start', behavior: 'smooth' })
    clearTimeout(timer)
    this.setState({ key: 'isRealScroll', value: false })
    timer = setTimeout(() => {
      this.setState({ key: 'isRealScroll', value: true })
    }, 1000)
  }
}
</script>

<style>

</style>
