// demo/vue/m-app-vue3/src/views/light/login/Login.vue
<template>
  <div>
    <input v-model="username" autofocus />
  </div>
  <div>
    <input v-model="password" :type="visible ? 'text' : 'password'" @keyup.enter="handleLogin" />
    <Icon
      :name="visible ? 'show' : 'hide'"
      className="m-login-icon"
      @onClick="handleVisible"
    ></Icon>
  </div>
  <button @click="handleLogin">登录</button>
</template>

<script>
import { reactive, toRefs } from "vue"
import { useRouter } from 'vue-router'
import Icon from "../../../components/light/Icon"
import Api from "../../../api"

export default {
  components: {
    Icon,
  },
  setup() {
    const state = reactive({
      username: "admin",
      password: "123456",
      visible: false,
    })

    const router = useRouter()

    const handleVisible = () => {
      const { visible } = state
      state.visible = !visible
    }

    const handleLogin = () => {
      const { username, password } = state
      Api.login({ username, password }).then((res) => {
        if (res.code === 200) {
          router.push('/light/index/home')
        }
      })
    }

    return {
      ...toRefs(state),
      handleVisible,
      handleLogin
    }
  },
}
</script>

<style></style>

// m-app-1707B/react/m-book-test3/src/views/Login.js
import React, { Component } from 'react'
import Icon from '../components/Icon'
import Api from '../api'

export default class Login extends Component {
  constructor(props) {
    super(props)
    this.state = {
      username: 'admin',
      password: '123456',
      visible: false
    }
  }

  handleInput(field, value) {
    this.setState({
      [field]: value
    })
  }

  handleVisible() {
    this.setState({
      visible: !this.state.visible
    })
  }

  handleLogin() {
    const { username, password } = this.state
    Api.login({ username, password }).then(res => {
      console.log(res)
      if (res.code === 200) {
        this.props.history.push('/index/home')
      }
    })
  }

  handleEnter(e) {
    if (e.keyCode === 13) {
      this.handleLogin()
    }
  }

  render() {
    const { username, password, visible } = this.state
    return (
      <div>
        <div>
          <input value={ username } onChange={ (e) => this.handleInput('username', e.target.value) } placeholder="请输入用户名" autoFocus></input>
        </div>
        <div>
          <input value={ password } type={ visible ? 'text' : 'password'} 
            onChange={ (e) => this.handleInput('password', e.target.value) }
            onKeyUp={ (e) => this.handleEnter(e) } 
            placeholder="请输入密码"></input>
          <Icon name={ visible ? 'show' : 'hide' } onClick={() => this.handleVisible() } className="m-login-icon"></Icon>
        </div>
        <button onClick={ () => this.handleLogin()}>登录</button>
      </div>
    )
  }
}
